modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
[[mods]]
modId="fantazia"
version="${file.jarVersion}"
displayName="Fantazia"
logoFile="FTZ_logo.png"
credits=""
authors="ArkadiyHimself"
description='''

'''
[[dependencies.fantazia]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fantazia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.21)"
    ordering="NONE"
    side="BOTH"
